# yaml-language-server: $schema=https://raw.githubusercontent.com/symfony/routing/7.4/Loader/schema/routing.schema.json
storefront:
    resource: ../../Storefront/**/*Controller.php
    type: attribute

imported_routes:
    resource: ../../**/*Route.php
    type: attribute
